// https://developers.sift.com/docs/curl/apis-overview
// Snippet to gather events information
// CMD + / to uncomment
//
// (() => {
//   const rgx = /^\s*\/\/\s*Sample\s+(\$\w+)\s+event[^\r\n]*/i;
//   const result = Array.from(
//     document.querySelectorAll(
//       ".prettyprint.lang.curl.code-partial.prettyprinted"
//     )
//   )
//     .map((item) => {
//       const [templateName, eventType] = item.textContent.match(rgx) || [];

//       if (!eventType) {
//         return null;
//       }

//       Array.from(item.querySelectorAll(".com")).forEach((commentNode) =>
//         commentNode.remove()
//       );

//       return { templateName, eventType, code: item.textContent.trim() };
//     })
//     .reduce((res, item) => {
//       if (!item) {
//         return res;
//       }

//       let { templateName, eventType, code } = item;

//       try {
//         code = JSON.parse(code);
//       } catch (error) {
//         console.log(`Template "${templateName}" has syntax errors.`);
//       }

//       if (!res[eventType]) res[eventType] = {};

//       res[eventType][templateName.replace(/^\s*\/\/\s*/, "")] = code;

//       return res;
//     }, {});

//   return result;
// })();

export const getCustomEventPayload = (event) => ({
  $type: event,
  $api_key: "YOUR_API_KEY",
  $browser: {
    $user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
    $accept_language: "en-US",
    $content_language: "en-GB",
  },
  $app: {
    $os: "iOS",
    $os_version: "10.1.3",
    $device_manufacturer: "Apple",
    $device_model: "iPhone 4,2",
    $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
    $app_name: "Calculator",
    $app_version: "3.2.7",
    $client_language: "en-US",
  },
});

export const getEventsData = () => ({
  $create_account: {
    "Sample $create_account event": {
      $type: "$create_account",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $name: "Bill Jones",
      $phone: "1-415-555-6040",
      $referrer_user_id: "janejane101",
      $payment_methods: [
        {
          $payment_type: "$credit_card",
          $card_bin: "542486",
          $card_last4: "4444",
        },
      ],
      $billing_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6040",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $shipping_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $promotions: [
        {
          $promotion_id: "FriendReferral",
          $status: "$success",
          $referrer_user_id: "janejane102",
          $credit_point: {
            $amount: 100,
            $credit_point_type: "account karma",
          },
        },
      ],
      $social_sign_on_type: "$twitter",
      $account_types: ["merchant", "premium"],
      $ip: "54.208.214.78",
      twitter_handle: "billyjones",
      work_phone: "1-347-555-5921",
      location: "New London, NH",
      referral_code: "MIKEFRIENDS",
      email_confirmed_status: "$pending",
      phone_confirmed_status: "$pending",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $add_item_to_cart: {
    "Sample $add_item_to_cart event": {
      $type: "$add_item_to_cart",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $item: {
        $item_id: "B004834GQO",
        $product_title: "The Slanket Blanket-Texas Tea",
        $price: 39990000,
        $currency_code: "USD",
        $upc: "6786211451001",
        $sku: "004834GQ",
        $brand: "Slanket",
        $manufacturer: "Slanket",
        $category: "Blankets & Throws",
        $tags: ["Awesome", "Wintertime specials"],
        $color: "Texas Tea",
        $quantity: 16,
      },
      $brand_name: "sift",
      $site_domain: "sift.com",
      $site_country: "US",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $add_promotion: {
    "Sample $add_promotion event": {
      $type: "$add_promotion",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $promotions: [
        {
          $promotion_id: "NewRideDiscountMay2016",
          $status: "$success",
          $description: "$5 off your first 5 rides",
          $referrer_user_id: "elon-m93903",
          $discount: {
            $amount: 5000000,
            $currency_code: "USD",
          },
        },
      ],
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $chargeback: {
    "Sample $chargeback event": {
      $type: "$chargeback",
      $api_key: "YOUR_API_KEY",
      $order_id: "ORDER-123124124",
      $transaction_id: "719637215",
      $user_id: "billy_jones_301",
      $chargeback_state: "$lost",
      $chargeback_reason: "$duplicate",
      $ip: "54.208.214.78",
    },
  },
  $content_status: {
    "Sample $content_status event": {
      $type: "$content_status",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $content_id: "9671500641",
      $status: "$paused",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $create_content: {
    "Sample $create_content event for comments": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "comment-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $comment: {
        $body: "Congrats on the new role!",
        $contact_email: "alex_301@domain.com",
        $parent_comment_id: "comment-23407",
        $root_content_id: "listing-12923213",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "An old picture",
          },
        ],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $create_content event for listings": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "listing-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $listing: {
        $subject: "2 Bedroom Apartment for Rent",
        $body:
          "Capitol Hill Seattle brand new condo. 2 bedrooms and 1 full bath.",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Bill Jones",
          $phone: "1-415-555-6041",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $listed_items: [
          {
            $price: 2950000000,
            $currency_code: "USD",
            $tags: ["heat", "washer/dryer"],
          },
        ],
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "Billy's picture",
          },
        ],
        $expiration_time: 1549063157000,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $create_content event for messages": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "message-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $message: {
        $body: "Let’s meet at 5pm",
        $contact_email: "alex_301@domain.com",
        $recipient_user_ids: ["fy9h989sjphh71"],
        $root_content_id: "listing-123",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "My hike today!",
          },
        ],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $create_content event for posts": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "post-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $post: {
        $subject: "My new apartment!",
        $body: "Moved into my new apartment yesterday.",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Bill Jones",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $categories: ["Personal"],
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "View from the window!",
          },
        ],
        $expiration_time: 1549063157000,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $create_content event for profiles": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "profile-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "active",
      $ip: "255.255.255.0",
      $profile: {
        $body: "Hi! My name is Alex and I just moved to New London!",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Alex Smith",
          $phone: "1-415-555-6041",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "Alex’s picture",
          },
        ],
        $categories: ["Friends", "Long-term dating"],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $create_content event for reviews": {
      $type: "$create_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "review-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $review: {
        $subject: "Amazing Tacos!",
        $body: "I ate the tacos.",
        $contact_email: "alex_301@domain.com",
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $reviewed_content_id: "listing-234234",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e2697726618",
            $link: "https://www.domain.com/file.png",
            $description: "Calamari tacos.",
          },
        ],
        $rating: 4.5,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $create_order: {
    "Sample $create_order event": {
      $type: "$create_order",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $order_id: "ORDER-28168441",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $amount: 115940000,
      $currency_code: "USD",
      $billing_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $payment_methods: [
        {
          $payment_type: "$credit_card",
          $payment_gateway: "$braintree",
          $card_bin: "542486",
          $card_last4: "4444",
        },
      ],
      $ordered_from: {
        $store_id: "123",
        $store_address: {
          $name: "Bill Jones",
          $phone: "1-415-555-6040",
          $address_1: "2100 Main Street",
          $address_2: "Apt 3B",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
      },
      $brand_name: "sift",
      $site_domain: "sift.com",
      $site_country: "US",
      $shipping_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $expedited_shipping: true,
      $shipping_method: "$physical",
      $shipping_carrier: "UPS",
      $shipping_tracking_numbers: ["1Z204E380338943508", "1Z204E380338943509"],
      $items: [
        {
          $item_id: "12344321",
          $product_title: "Microwavable Kettle Corn: Original Flavor",
          $price: 4990000,
          $upc: "097564307560",
          $sku: "03586005",
          $brand: "Peters Kettle Corn",
          $manufacturer: "Peters Kettle Corn",
          $category: "Food and Grocery",
          $tags: ["Popcorn", "Snacks", "On Sale"],
          $quantity: 4,
        },
        {
          $item_id: "B004834GQO",
          $product_title: "The Slanket Blanket-Texas Tea",
          $price: 39990000,
          $upc: "6786211451001",
          $sku: "004834GQ",
          $brand: "Slanket",
          $manufacturer: "Slanket",
          $category: "Blankets & Throws",
          $tags: ["Awesome", "Wintertime specials"],
          $color: "Texas Tea",
          $quantity: 2,
        },
      ],
      $ip: "54.208.214.78",
      $seller_user_id: "slinkys_emporium",
      $promotions: [
        {
          $promotion_id: "FirstTimeBuyer",
          $status: "$success",
          $description: "$5 off",
          $discount: {
            $amount: 5000000,
            $currency_code: "USD",
            $minimum_purchase_amount: 25000000,
          },
        },
      ],
      digital_wallet: "apple_pay",
      coupon_code: "dollarMadness",
      shipping_choice: "FedEx Ground Courier",
      is_first_time_buyer: false,
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $flag_content: {
    "Sample $flag_content event": {
      $type: "$flag_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $content_id: "9671500641",
      $flagged_by: "jamieli89",
      $reason: "$toxic",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $ip: "54.208.214.78",
    },
  },
  $link_session_to_user: {
    "Sample $link_session_to_user event": {
      $type: "$link_session_to_user",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $ip: "54.208.214.78",
    },
  },
  $login: {
    "Sample $login event": {
      $type: "$login",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $login_status: "$success",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $ip: "128.148.1.135",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $failure_reason: "$account_unknown",
      $username: "billjones1@example.com",
      $account_types: ["merchant", "premium"],
      $social_sign_on: "$linkedin",
      $brand_name: "sift",
      $site_domain: "sift.com",
      $site_country: "US",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $logout: {
    "Sample $logout event": {
      $type: "$logout",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $order_status: {
    "Sample $order_status event": {
      $type: "$order_status",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $order_id: "ORDER-28168441",
      $order_status: "$canceled",
      $reason: "$payment_risk",
      $source: "$manual_review",
      $analyst: "someone@your-site.com",
      $webhook_id: "3ff1082a4aea8d0c58e3643ddb7a5bb87ffffeb2492dca33",
      $description: "Canceling because multiple fraudulent users on device",
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $remove_item_from_cart: {
    "Sample $remove_item_from_cart event": {
      $type: "$remove_item_from_cart",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $item: {
        $item_id: "B004834GQO",
        $product_title: "The Slanket Blanket-Texas Tea",
        $price: 39990000,
        $currency_code: "USD",
        $quantity: 2,
        $upc: "6786211451001",
        $sku: "004834GQ",
        $brand: "Slanket",
        $manufacturer: "Slanket",
        $category: "Blankets & Throws",
        $tags: ["Awesome", "Wintertime specials"],
        $color: "Texas Tea",
      },
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $security_notification: {
    "Sample $security_notification event": {
      $type: "$security_notification",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $notification_status: "$sent",
      $notification_type: "$email",
      $notified_value: "billy123@domain.com",
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $transaction: {
    "Sample $transaction event": {
      $type: "$transaction",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $amount: 506790000,
      $currency_code: "USD",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $transaction_type: "$sale",
      $transaction_status: "$failure",
      $decline_category: "$bank_decline",
      $order_id: "ORDER-123124124",
      $transaction_id: "719637215",
      $ip: "54.208.214.78",
      $billing_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $brand_name: "sift",
      $site_domain: "sift.com",
      $site_country: "US",
      $ordered_from: {
        $store_id: "123",
        $store_address: {
          $name: "Bill Jones",
          $phone: "1-415-555-6040",
          $address_1: "2100 Main Street",
          $address_2: "Apt 3B",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
      },
      $payment_method: {
        $payment_type: "$credit_card",
        $payment_gateway: "$braintree",
        $card_bin: "542486",
        $card_last4: "4444",
      },
      $status_3ds: "$attempted",
      $triggered_3ds: "$processor",
      $merchant_initiated_transaction: false,
      $shipping_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $session_id: "gigtleqddo84l8cm15qe4il",
      $seller_user_id: "slinkys_emporium",
      digital_wallet: "apple_pay",
      coupon_code: "dollarMadness",
      shipping_choice: "FedEx Ground Courier",
      is_first_time_buyer: false,
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $update_account: {
    "Sample $update_account event": {
      $type: "$update_account",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $changed_password: true,
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $name: "Bill Jones",
      $phone: "1-415-555-6040",
      $referrer_user_id: "janejane102",
      $payment_methods: [
        {
          $payment_type: "$credit_card",
          $card_bin: "542486",
          $card_last4: "4444",
        },
      ],
      $billing_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $shipping_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $social_sign_on_type: "$twitter",
      $account_types: ["merchant", "premium"],
      $ip: "54.208.214.78",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $update_content: {
    "Sample $update_content event for comments": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "comment-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $comment: {
        $body: "Congrats on the new role!",
        $contact_email: "alex_301@domain.com",
        $parent_comment_id: "comment-23407",
        $root_content_id: "listing-12923213",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "An old picture",
          },
        ],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $update_content event for listings": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "listing-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $listing: {
        $subject: "2 Bedroom Apartment for Rent",
        $body:
          "Capitol Hill Seattle brand new condo. 2 bedrooms and 1 full bath.",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Bill Jones",
          $phone: "1-415-555-6041",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $listed_items: [
          {
            $price: 2950000000,
            $currency_code: "USD",
            $tags: ["heat", "washer/dryer"],
          },
        ],
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "Billy's picture",
          },
        ],
        $expiration_time: 1549063157000,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $update_content event for messages": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "message-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $message: {
        $body: "Let’s meet at 5pm",
        $contact_email: "alex_301@domain.com",
        $recipient_user_ids: ["fy9h989sjphh71"],
        $root_content_id: "listing-123",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "My hike today!",
          },
        ],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $update_content event for posts": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "post-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $post: {
        $subject: "My new apartment!",
        $body: "Moved into my new apartment yesterday.",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Bill Jones",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $categories: ["Personal"],
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "View from the window!",
          },
        ],
        $expiration_time: 1549063157000,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $update_content event for profiles": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "listing-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $profile: {
        $body: "Hi! My name is Alex and I just moved to New London!",
        $contact_email: "alex_301@domain.com",
        $contact_address: {
          $name: "Alex Smith",
          $phone: "1-415-555-6041",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "Alex’s picture",
          },
        ],
        $categories: ["Friends", "Long-term dating"],
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
    "Sample $update_content event for reviews": {
      $type: "$update_content",
      $api_key: "YOUR_API_KEY",
      $user_id: "fyw3989sjpqr71",
      $content_id: "review-23412",
      $session_id: "a234ksjfgn435sfg",
      $status: "$active",
      $ip: "255.255.255.0",
      $review: {
        $subject: "Amazing Tacos!",
        $body: "I ate the tacos.",
        $contact_email: "alex_301@domain.com",
        $locations: [
          {
            $city: "Seattle",
            $region: "Washington",
            $country: "US",
            $zipcode: "98112",
          },
        ],
        $reviewed_content_id: "listing-234234",
        $images: [
          {
            $md5_hash: "0cc175b9c0f1b6a831c399e269772661",
            $link: "https://www.domain.com/file.png",
            $description: "Calamari tacos.",
          },
        ],
        $rating: 4.5,
      },
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $update_order: {
    "Sample $update_order event": {
      $type: "$update_order",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $order_id: "ORDER-28168441",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $amount: 115940000,
      $currency_code: "USD",
      $billing_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $payment_methods: [
        {
          $payment_type: "$credit_card",
          $payment_gateway: "$braintree",
          $card_bin: "542486",
          $card_last4: "4444",
        },
      ],
      $brand_name: "sift",
      $site_domain: "sift.com",
      $site_country: "US",
      $ordered_from: {
        $store_id: "123",
        $store_address: {
          $name: "Bill Jones",
          $phone: "1-415-555-6040",
          $address_1: "2100 Main Street",
          $address_2: "Apt 3B",
          $city: "New London",
          $region: "New Hampshire",
          $country: "US",
          $zipcode: "03257",
        },
      },
      $shipping_address: {
        $name: "Bill Jones",
        $phone: "1-415-555-6041",
        $address_1: "2100 Main Street",
        $address_2: "Apt 3B",
        $city: "New London",
        $region: "New Hampshire",
        $country: "US",
        $zipcode: "03257",
      },
      $expedited_shipping: true,
      $shipping_method: "$physical",
      $shipping_carrier: "UPS",
      $shipping_tracking_numbers: ["1Z204E380338943508", "1Z204E380338943509"],
      $items: [
        {
          $item_id: "12344321",
          $product_title: "Microwavable Kettle Corn: Original Flavor",
          $price: 4990000,
          $upc: "097564307560",
          $sku: "03586005",
          $brand: "Peters Kettle Corn",
          $manufacturer: "Peters Kettle Corn",
          $category: "Food and Grocery",
          $tags: ["Popcorn", "Snacks", "On Sale"],
          $quantity: 4,
        },
        {
          $item_id: "B004834GQO",
          $product_title: "The Slanket Blanket-Texas Tea",
          $price: 39990000,
          $upc: "6786211451001",
          $sku: "004834GQ",
          $brand: "Slanket",
          $manufacturer: "Slanket",
          $category: "Blankets & Throws",
          $tags: ["Awesome", "Wintertime specials"],
          $color: "Texas Tea",
          $quantity: 2,
        },
      ],
      $ip: "54.208.214.78",
      $seller_user_id: "slinkys_emporium",
      $promotions: [
        {
          $promotion_id: "FirstTimeBuyer",
          $status: "$success",
          $description: "$5 off",
          $discount: {
            $amount: 5000000,
            $currency_code: "USD",
            $minimum_purchase_amount: 25000000,
          },
        },
      ],
      digital_wallet: "apple_pay",
      coupon_code: "dollarMadness",
      shipping_choice: "FedEx Ground Courier",
      is_first_time_buyer: false,
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $update_password: {
    "Sample $update_password event": {
      $type: "$update_password",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $status: "$success",
      $reason: "$forced_reset",
      $user_email: "billjones1@example.com",
      $verification_phone_number: "+123456789012",
      $ip: "128.148.1.135",
      $browser: {
        $user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
        $accept_language: "en-US",
        $content_language: "en-GB",
      },
      $app: {
        $os: "iOS",
        $os_version: "10.1.3",
        $device_manufacturer: "Apple",
        $device_model: "iPhone 4,2",
        $device_unique_id: "A3D261E4-DE0A-470B-9E4A-720F3D3D22E6",
        $app_name: "Calculator",
        $app_version: "3.2.7",
        $client_language: "en-US",
      },
    },
  },
  $verification: {
    "Sample $verification event": {
      $type: "$verification",
      $api_key: "YOUR_API_KEY",
      $user_id: "billy_jones_301",
      $session_id: "gigtleqddo84l8cm15qe4il",
      $status: "$pending",
      $verified_event: "$login",
      $reason: "$automated_rule",
      $verification_type: "$sms",
      $verified_value: "14155551212",
      $ip: "54.208.214.78",
    },
  },
});
